name: optiven
description: A real estate app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  line_awesome_icons: ^1.0.4+2
  webview_flutter: ^0.3.22+1
  flutter_user_agent: ^1.2.2
  intl: ^0.16.1
  path_provider: ^1.6.11
  sqflite: ^1.3.1
  http: ^0.12.1
  flutter_bloc: ^4.0.0

  flutter_blurhash: ^0.5.0

  share: ^0.6.4+3
  injectable: ^0.4.0+1

  kf_drawer: ^1.1.2

  division: ^0.8.8
  animations: ^1.1.1
  flutter_screenutil: ^1.1.0
  motion_widget: ^1.0.2
  flutter_phone_state: ^0.5.8

  flutter_full_pdf_viewer: ^1.0.6
  photo_view: ^0.9.2
  youtube_player_flutter: ^7.0.0+6
  carousel_slider: ^2.2.1
  like_button: ^1.0.1
  get: ^3.2.1
  email_launcher: ^1.0.0
  get_it: ^4.0.2
  json_annotation: ^3.0.1
  freezed_annotation: ^0.7.1
  data_connection_checker: ^0.3.4
  cached_network_image: ^2.2.0+1
  rxdart: ^0.24.0
  dartz: ^0.9.0
  kt_dart: ^0.7.0+1
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.5
  firebase_core: ^0.4.4+3
  shimmer: ^1.1.1
  dart_random_choice: ^0.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  injectable_generator: ^0.4.1
  freezed: ^0.10.7
  json_serializable: ^3.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/homepage_image.jpg
    - assets/images/optiven_logo2.png
    - assets/images/partners.jpg
    - assets/images/foundation.jpg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
